### ISSUE TITLE
AWS技術検証

### ISSUE THREAD

**Issue by TasukuFuruki** [team-toypoodle/JamNavigator#1]

**Comment by mtonosaki** [comment]
- AmplifyとSwiftの連携
- Cognitoを使った サインアップ、サインイン、サインアウト（アクセストークンが生きている時は自動ログイン）
- WebAPI（REST：Node.js＋Express）→　つかわない方向
- WebAPI（GraphQL→DynamoDB）
- S3ストレージ（アップロード、ダウンロード）
